<a href="https://colab.research.google.com/github/yebiFesseha/Excel-for-Excel-In-MachineLearning/blob/main/NN_ForwardPropagation_II.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Below we summarized what we have done in the previous NN_ForwardPropagation script with a function

We will run a 4 features input through a neural network with the below characteristics, we only work on FF propagation in this version as well:

* Dense Layer 1 sets of neurons = 15, and use ReLu for activation,
* Dense Layer 2 sets of neurons = 7, and use sigmoid for activation,
* Dense Layer 3 sets of neurons = 11, and use tanH for activation
* Finally for the 7 output layer use a siftmax function for activation

In [1]:
import numpy as np
import pandas as pd
import math
import seaborn as sns
import matplotlib.pyplot as plt
sns.set_theme(style='darkgrid')

In [2]:
# x input array (values), number of features input (nfeatures), nneurons=number of neurons
def postActivation(x,nneurons, func):
    np.random.seed(10)
    w = np.random.randn(x.shape[1], nneurons)
    iw =  np.dot(x,w)
    bias =  np.random.randn(iw.shape[0], iw.shape[1])
    y = np.add(iw, bias)
    return func(y)

def sigmoid(x):
    return 1 /(1 + np.exp(-x))
def ReLu(x):
  return np.maximum(0,x)
def tanH(x):
    return np.tanh(x)
def linear(x):
    return x
def softmax(x):
    return np.exp(x)/np.sum(np.exp(x))
def minMaxScalar(x):
  return (x-np.min(x, axis=0, keepdims=True))/ (np.max(x, axis=0, keepdims=True)-np.min(x, axis=0, keepdims=True))

In [3]:
# create a 4 features input array with 3 batches of input
np.random.seed(1)
inputFeatures = int(input("Enter the number of input features: " ))
inputBatches = int(input("Enter the number of input batches: " ))
print("\nThe input array is:")
X = np.random.randint(-48,100,(inputBatches,inputFeatures)) 
X

Enter the number of input features: 4
Enter the number of input batches: 3

The input array is:


array([[-11,  92,  24,  89],
       [ 85,  31,  96,  81],
       [ 23,  86, -23, -28]])

In [4]:
# Use a min-max feature scaling
X = minMaxScalar(X)
X

array([[0.        , 1.        , 0.39495798, 1.        ],
       [1.        , 0.        , 1.        , 0.93162393],
       [0.35416667, 0.90163934, 0.        , 0.        ]])

In [5]:
# Dense Layer 1 sets of neurons = 15, and use ReLu for activation,
postActivation(X, 
               15, 
               ReLu)

array([[0.        , 0.        , 1.62850617, 1.16382355, 0.        ,
        0.        , 0.        , 0.        , 3.22688192, 1.5549131 ,
        2.45632315, 2.81617613, 1.72862872, 0.41228436, 0.24799782],
       [3.33376616, 0.        , 0.        , 0.        , 0.99446   ,
        1.43587828, 2.6798628 , 0.        , 1.69772882, 0.        ,
        0.        , 3.03429821, 0.        , 0.65160629, 0.        ],
       [1.98066537, 0.        , 0.        , 0.58165473, 0.        ,
        0.        , 0.        , 0.36793121, 2.97889888, 0.        ,
        1.7789411 , 0.        , 0.        , 0.58936398, 0.48949543]])

In [6]:
# Dense Layer 2 sets of neurons = 7, and use sigmoid for activation,
postActivation(postActivation(X, 15, ReLu), # the input is the output of the first dense layer
               7, 
               sigmoid)

array([[9.99331532e-01, 8.06645569e-02, 7.20344015e-02, 9.99986502e-01,
        9.98924733e-01, 1.96825852e-03, 2.63477662e-01],
       [9.99970885e-01, 4.66134373e-01, 1.03873926e-05, 9.97940879e-01,
        9.95047614e-01, 4.32037096e-04, 9.91582042e-01],
       [9.99725754e-01, 9.72038520e-01, 1.81118054e-02, 8.63075912e-01,
        9.92513524e-01, 9.59517242e-01, 9.18462066e-01]])

In [7]:
# Dense Layer 3 sets of neurons = 11, and use tanH for activation
postActivation(postActivation(postActivation(X, 15, ReLu), 7, sigmoid),  # the input is the output of the second dense layer
               11, 
               tanH)

array([[ 0.7870723 ,  0.45466352, -0.98418354,  0.99256268,  0.99134357,
        -0.87085202, -0.65371487,  0.88925958, -0.99545582, -0.00442656,
         0.5706909 ],
       [ 0.95371081, -0.96677388, -0.43026494,  0.73144688,  0.86397885,
        -0.41334169,  0.0699083 ,  0.99864058, -0.91488273,  0.83580658,
        -0.6035809 ],
       [ 0.46025213,  0.95181649, -0.96761706, -0.2385235 ,  0.94031025,
        -0.66687966, -0.87294488,  0.99946701, -0.88982659,  0.59188523,
        -0.99827085]])

In [8]:
# the 7 output layer use a siftmax function for activation
postActivation(postActivation(postActivation(postActivation(X, 15, ReLu), 7, sigmoid),11,tanH), # the input to the output layer is the output of the third dense layer
               7,
               softmax)

array([[2.87880511e-04, 1.48958291e-03, 2.82624843e-02, 2.56524080e-02,
        4.75232652e-01, 2.34671494e-03, 7.86132516e-02],
       [7.26041300e-05, 3.05657674e-04, 7.08252674e-03, 2.55405028e-03,
        3.72604685e-03, 2.95407858e-04, 1.07861125e-01],
       [7.60821963e-04, 1.36350602e-03, 2.75410600e-03, 1.12034568e-03,
        1.02758447e-02, 1.20663794e-04, 2.49822320e-01]])