### Basic Neural Network Concept : Forward Propagation
* I will create a Neural network with the following characteristcs:
An input layer with 3 inputs, A deep layer with 3 sets of neurons and an ouput layer.
* The first sets of neurons of the deep layer will have 7 neurons, the second set will have 33 neurons and the third set will have 21 neurons.
And an output layer with 4 outputs/neurons.
* For educational purpose I will implement all major activation functions throughout the deep layer architecture: sigmoid, ReLu, TanH and Softmax at the output layer.

* The goal is to build a basic NN architecture to gain a deeper understanding of the forward propagation concept of a neural network. So the choice of the deep layer, parameters and activation functions are done in a haphazard fashion

* Here is the architecture of the network: ((3x4),(4x7),(7x33),(33x21),(21x9))

In [21]:
import numpy as np
import pandas as pd
import math
import seaborn as sns
import matplotlib.pyplot as plt
sns.set_theme(style='darkgrid')

In [3]:
# First generate a batch of inputs using numpy This is the architecture of the network: ((3x4),(4x7),(7x33),(33x21),(21x9))
# Lets have 3 bathces of data of 4 input values each
np.random.seed(1)
X = np.random.randint(-10,10,(3,4)) # 
print(X)

[[ -5   1   2  -2]
 [ -1   1  -5   5]
 [-10   6  -9   2]]


---
#### **The First Neuron sets of the Deep Layer**

In [4]:
# The set of neurons of the first deep layer are 7, hence we need 4 input by 7 neurons sets of weights
np.random.seed(1)
weights1 = np.random.randn(4,7)
inputBYweight1 = np.dot(X, weights1)
print(inputBYweight1)

[[ -8.90484225  -0.62514281   1.04164329   3.26952231  -4.93529564
   12.59668716  -9.43781266]
 [ -2.33078093  10.93820545   3.65341411  11.4286484   -6.55525637
   -1.5494057   -1.3046174 ]
 [-28.7251726   19.73400156   6.34233782  29.2047715  -22.76229999
   15.58976637 -11.71841004]]


In [5]:
# For each first 7 sets of neurons of the deep layer we need 7 bias values which will be added element wise,
# Since for the previuos output we have a 3x7 ouput we will add a 3x7 matrix of biases
np.random.seed(1)
bias1 = np.random.randint(-5,5, (3,7))
print(bias1)

[[ 0  3  4  0 -5 -5 -4]
 [ 2  1  4 -3 -1  0 -3]
 [-1 -3 -1  2  2  4 -4]]


In [6]:
preactivation1 = np.add(inputBYweight1, bias1)
print(preactivation1)

[[ -8.90484225   2.37485719   5.04164329   3.26952231  -9.93529564
    7.59668716 -13.43781266]
 [ -0.33078093  11.93820545   7.65341411   8.4286484   -7.55525637
   -1.5494057   -4.3046174 ]
 [-29.7251726   16.73400156   5.34233782  31.2047715  -20.76229999
   19.58976637 -15.71841004]]


In [67]:
# For the first sets of neurons of the deep layer we will use a linear function for demonstration purpose
f = lambda x: x
postactivation1 = f(preactivation1)
print(postactivation1)
print(f"\n At the output of the first sets of neurons of the deep layer we have a {postactivation1.shape} matrix.")

[[ -8.90484225   2.37485719   5.04164329   3.26952231  -9.93529564
    7.59668716 -13.43781266]
 [ -0.33078093  11.93820545   7.65341411   8.4286484   -7.55525637
   -1.5494057   -4.3046174 ]
 [-29.7251726   16.73400156   5.34233782  31.2047715  -20.76229999
   19.58976637 -15.71841004]]

 At the output of the first sets of neurons of the deep layer we have a (3, 7) matrix.


In [68]:
# Here is the activation using a sigmoid function, the values are between 0 and 1
def sigmoid(x):
  return 1/(1 + np.exp(-x))

postactivation1 = sigmoid(preactivation1)
print(postactivation1)
print(f"\n At the output of the first sets of neurons of the deep layer we have a {postactivation1.shape} matrix.")

[[1.35711673e-04 9.14889835e-01 9.93578385e-01 9.63368318e-01
  4.84322774e-05 9.99498140e-01 1.45892000e-06]
 [4.18050624e-01 9.99993464e-01 9.99525803e-01 9.99781531e-01
  5.23078200e-04 1.75172120e-01 1.33260693e-02]
 [1.23174715e-13 9.99999946e-01 9.95238112e-01 1.00000000e+00
  9.61717863e-10 9.99999997e-01 1.49135553e-07]]

 At the output of the first sets of neurons of the deep layer we have a (3, 7) matrix.


---
#### **The second Neuron sets of the Deep Layer**

In [69]:
#For the second sets of neurons of the deep layer we have 33 neurons, hence we need 7x33 weights multiplied by postactivation1: resulting 3x33 dot product 
np.random.seed(1)
weights2 = np.random.randn(7,33)
inputBYweight2 = np.dot(postactivation1, weights2)
print(inputBYweight2)

[[ 0.84910096  1.45097673  3.55299857  0.1683923  -2.54380836 -0.68445056
   1.90238386  3.93541595 -1.66571775 -2.90564241  1.04962985  0.876872
  -0.33773138  2.42662996  0.55308937 -1.02387207 -0.20079963  1.14761069
  -0.3892589   0.04287336 -1.20919307  0.72304894  0.1517308   3.3974926
   3.86516014 -0.18501466  1.99710257  2.14673251  3.00307784  0.04952331
  -1.40935259  0.91791279 -0.84695487]
 [ 1.64239104  0.33206306  3.20778991 -2.16388476 -0.59319238 -0.98913715
   1.94135069  1.52554426 -1.45790474 -3.14307673  1.97612442 -1.09597747
  -0.28110436  1.73929441  1.45153428 -0.42025495 -0.5418444   0.40452171
  -1.51713186  0.31484335 -1.15983229  0.72387719  0.37425003  3.50728383
   4.48061482 -1.46810014  1.74302755  0.20897229  2.08918323 -0.27478483
  -0.36205925  0.28799123 -1.50922514]
 [ 0.80436409  1.3805403   3.60054489  0.08703482 -2.50560389 -0.58408981
   1.97218824  3.94904305 -1.77583261 -2.98227962  1.19400874  0.83317975
  -0.38014508  2.47552833  0.69966821

In [70]:
# For each second sets of 33 of the deep layer we need 33 bias values which will be added element wise,
# Since for the previuos output we have a 3x33 ouput we will add a 3x33 matrix of biases
np.random.seed(1)
bias2 = np.random.randint(-5,5, (3,33))
print(bias2)

[[ 0  3  4  0 -5 -5 -4  2  1  4 -3 -1  0 -3 -1 -3 -1  2  2  4 -4  2 -5  1
   4  4  2  1  4 -4 -5 -4  3]
 [ 3 -2  4  3  2 -2  1  0 -4  4 -2 -1  3 -4 -1 -5 -2  4 -3 -5 -1  4 -3  2
   2  4  3  1  4 -2  2  2 -1]
 [ 0  4 -2  1  3 -5 -3  2  2  4  2 -2 -5  3  2  2 -4 -4 -2 -5  3  1 -1  0
   1 -3  0  2  3 -1 -1  2  2]]


In [71]:
#pre activation 
preactivation2 = np.add(inputBYweight2, bias2)
print(preactivation2)

[[ 0.84910096  4.45097673  7.55299857  0.1683923  -7.54380836 -5.68445056
  -2.09761614  5.93541595 -0.66571775  1.09435759 -1.95037015 -0.123128
  -0.33773138 -0.57337004 -0.44691063 -4.02387207 -1.20079963  3.14761069
   1.6107411   4.04287336 -5.20919307  2.72304894 -4.8482692   4.3974926
   7.86516014  3.81498534  3.99710257  3.14673251  7.00307784 -3.95047669
  -6.40935259 -3.08208721  2.15304513]
 [ 4.64239104 -1.66793694  7.20778991  0.83611524  1.40680762 -2.98913715
   2.94135069  1.52554426 -5.45790474  0.85692327 -0.02387558 -2.09597747
   2.71889564 -2.26070559  0.45153428 -5.42025495 -2.5418444   4.40452171
  -4.51713186 -4.68515665 -2.15983229  4.72387719 -2.62574997  5.50728383
   6.48061482  2.53189986  4.74302755  1.20897229  6.08918323 -2.27478483
   1.63794075  2.28799123 -2.50922514]
 [ 0.80436409  5.3805403   1.60054489  1.08703482  0.49439611 -5.58408981
  -1.02781176  5.94904305  0.22416739  1.01772038  3.19400874 -1.16682025
  -5.38014508  5.47552833  2.69966821

In [72]:
# For the second sets of neurons of the deep layer we will use a ReLu function for activation
def ReLu(x):
  return max(0,x)

# using pandas and apply lambda, then returning the data frame back to a numpy array
postactivation2 = np.array(pd.DataFrame(preactivation2).applymap(lambda x: ReLu(x)))
postactivation2

array([[0.84910096, 4.45097673, 7.55299857, 0.1683923 , 0.        ,
        0.        , 0.        , 5.93541595, 0.        , 1.09435759,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 3.14761069, 1.6107411 , 4.04287336,
        0.        , 2.72304894, 0.        , 4.3974926 , 7.86516014,
        3.81498534, 3.99710257, 3.14673251, 7.00307784, 0.        ,
        0.        , 0.        , 2.15304513],
       [4.64239104, 0.        , 7.20778991, 0.83611524, 1.40680762,
        0.        , 2.94135069, 1.52554426, 0.        , 0.85692327,
        0.        , 0.        , 2.71889564, 0.        , 0.45153428,
        0.        , 0.        , 4.40452171, 0.        , 0.        ,
        0.        , 4.72387719, 0.        , 5.50728383, 6.48061482,
        2.53189986, 4.74302755, 1.20897229, 6.08918323, 0.        ,
        1.63794075, 2.28799123, 0.        ],
       [0.80436409, 5.3805403 , 1.60054489, 1.08703482, 0.49439611,
        0.        , 0.    

In [73]:
#Or the same ReLu function can be applied using a one line numpy code too
postactivation2 =np.maximum(0, preactivation2)
print(postactivation2)
print(f"\n At the output of the second sets of neurons of the deep layer we have a {postactivation2.shape} matrix.")

[[0.84910096 4.45097673 7.55299857 0.1683923  0.         0.
  0.         5.93541595 0.         1.09435759 0.         0.
  0.         0.         0.         0.         0.         3.14761069
  1.6107411  4.04287336 0.         2.72304894 0.         4.3974926
  7.86516014 3.81498534 3.99710257 3.14673251 7.00307784 0.
  0.         0.         2.15304513]
 [4.64239104 0.         7.20778991 0.83611524 1.40680762 0.
  2.94135069 1.52554426 0.         0.85692327 0.         0.
  2.71889564 0.         0.45153428 0.         0.         4.40452171
  0.         0.         0.         4.72387719 0.         5.50728383
  6.48061482 2.53189986 4.74302755 1.20897229 6.08918323 0.
  1.63794075 2.28799123 0.        ]
 [0.80436409 5.3805403  1.60054489 1.08703482 0.49439611 0.
  0.         5.94904305 0.22416739 1.01772038 3.19400874 0.
  0.         5.47552833 2.69966821 0.998344   0.         0.
  0.         0.         1.77472732 1.70501581 0.         3.51750988
  5.01830008 0.         2.1172998  4.14222307 6.1

---
#### **The Third Neuron sets of the Deep Layer**

In [74]:
#The third sets of neurons of the deep layer is 21, hence we need 33x21 sets of weights
np.random.seed(1)
weights3 = np.random.randn(33, 21)
inputBYweight3 = np.dot(postactivation2, weights3) # the input in this case is postactivation2, which is 3x33
print(inputBYweight3)

[[  9.65145599   7.94248274   5.10728363  -1.53264199   6.39290893
   31.95248638  31.0166038    0.95876436  19.49883145  -6.14903326
  -12.57330506   4.04717516 -21.39005729  14.69721029 -12.63844812
  -11.48090915  -3.48023319   1.38327213  -3.79097631  44.57247557
  -21.75928771]
 [ -4.74780808  16.14264673   2.79700133 -11.05146606  25.85336367
   17.92351264  26.43746559   0.15962003  20.19806203 -10.71463663
   -5.66768308  -5.89853898 -29.50577205  20.0251934  -10.07174736
   -2.68195466   9.67766109 -11.64054959  -3.79086602  42.59277253
   -8.30682275]
 [ 16.19150393  -5.45235303   9.03058581  -7.64387712  -2.12400786
   30.47399739  37.88033217  -1.71037722   9.98650258  -6.13439905
    4.8860517    5.78051499 -17.57091622   5.33099276 -15.14309012
  -12.04650379   9.22591893   1.1859063    1.80604282  26.43480521
   -4.45520874]]


In [75]:
# For each 21 neurons of the third sets of neurons of the deep layer we need 21 bias values of 3 batches to be added element wise, hence 3x21
np.random.seed(1)
bias3 = np.random.randint(-5,5, (3,21))
print(bias3)

[[ 0  3  4  0 -5 -5 -4  2  1  4 -3 -1  0 -3 -1 -3 -1  2  2  4 -4]
 [ 2 -5  1  4  4  2  1  4 -4 -5 -4  3  3 -2  4  3  2 -2  1  0 -4]
 [ 4 -2 -1  3 -4 -1 -5 -2  4 -3 -5 -1  4 -3  2  2  4  3  1  4 -2]]


In [76]:
#pre activation 
preactivation3 = np.add(inputBYweight3, bias3)
print(preactivation3)

[[  9.65145599  10.94248274   9.10728363  -1.53264199   1.39290893
   26.95248638  27.0166038    2.95876436  20.49883145  -2.14903326
  -15.57330506   3.04717516 -21.39005729  11.69721029 -13.63844812
  -14.48090915  -4.48023319   3.38327213  -1.79097631  48.57247557
  -25.75928771]
 [ -2.74780808  11.14264673   3.79700133  -7.05146606  29.85336367
   19.92351264  27.43746559   4.15962003  16.19806203 -15.71463663
   -9.66768308  -2.89853898 -26.50577205  18.0251934   -6.07174736
    0.31804534  11.67766109 -13.64054959  -2.79086602  42.59277253
  -12.30682275]
 [ 20.19150393  -7.45235303   8.03058581  -4.64387712  -6.12400786
   29.47399739  32.88033217  -3.71037722  13.98650258  -9.13439905
   -0.1139483    4.78051499 -13.57091622   2.33099276 -13.14309012
  -10.04650379  13.22591893   4.1859063    2.80604282  30.43480521
   -6.45520874]]


In [77]:
# For the third sets of neurons of the deep layer we will use a TanH function for activation
postactivation3 = np.tanh(preactivation3)
print(postactivation3)
print(f"\n At the output of the third sets of neurons of the deep layer we have a {postactivation3.shape} matrix.")

[[ 0.99999999  1.          0.99999998 -0.91087562  0.88380924  1.
   1.          0.99463076  1.         -0.97317504 -1.          0.995499
  -1.          1.         -1.         -1.         -0.99974326  0.99769931
  -0.94586351  1.         -1.        ]
 [-0.99182411  1.          0.99899358 -0.9999985   1.          1.
   1.          0.99951256  1.         -1.         -0.99999999 -0.99394556
  -1.          1.         -0.99998935  0.30773844  1.         -1.
  -0.99249619  1.         -1.        ]
 [ 1.         -0.99999933  0.99999979 -0.99981492 -0.99999041  1.
   1.         -0.99880332  1.         -0.99999998 -0.11345767  0.99985917
  -1.          0.98128148 -1.         -1.          1.          0.99953752
   0.99271971  1.         -0.99999506]]

 At the output of the third sets of neurons of the deep layer we have a (3, 21) matrix.


---
#### **The Output Layer**

In [78]:
#the ouput has 9 sets of output values, hence we need 21x9 sets of weights
np.random.seed(1)
weights4 = np.random.randn(21, 9)
inputBYweight4 = np.dot(postactivation3, weights4) # the input in this case is postactivation3, which is 3x21
print(inputBYweight4)

[[ 1.22872945  6.24038994  4.39754511 -1.80642748  0.84764017  6.85423473
  -1.24841725  2.68715695 -4.90458196]
 [-7.57504485  8.48461237  1.98490341  2.24088534 -1.32293682 14.67922447
  -3.70401638  0.36555547  1.41233782]
 [ 7.15640557  1.76189982  6.26399683 -4.42544893  1.74891468  3.79997641
   8.49144473 -5.69064914 -2.02363496]]


In [79]:
# For each 9 neurons of the output layer we need 9 bias values of 3 batches to be added element wise, hence 3x9
np.random.seed(1)
bias4 = np.random.randint(-2,2, (3,9))
print(bias4)

[[-1  1 -2 -2  1 -1  1 -1  1]
 [-2 -2 -1 -2  1 -1 -2  0 -1]
 [ 0 -2  0 -1  0 -2  1 -2  0]]


In [80]:
#pre activation 
preactivation4 = np.add(inputBYweight4, bias4)
print(preactivation4)

[[ 0.22872945  7.24038994  2.39754511 -3.80642748  1.84764017  5.85423473
  -0.24841725  1.68715695 -3.90458196]
 [-9.57504485  6.48461237  0.98490341  0.24088534 -0.32293682 13.67922447
  -5.70401638  0.36555547  0.41233782]
 [ 7.15640557 -0.23810018  6.26399683 -5.42544893  1.74891468  1.79997641
   9.49144473 -7.69064914 -2.02363496]]


In [81]:
# For the ouput layer we will use a softmax function for activation
def softmax(x):
  return np.exp(x)/np.sum(np.exp(x))

postactivation4 = softmax(preactivation4)
print(postactivation4)
print(f"\n The output layer has a {postactivation4.shape} matrix.")

[[1.41221890e-06 1.56685020e-03 1.23539743e-05 2.49721325e-08
  7.12830074e-06 3.91767062e-04 8.76354537e-07 6.07140265e-06
  2.26374594e-08]
 [7.80147895e-11 7.35863822e-04 3.00818264e-06 1.42949045e-06
  8.13422916e-07 9.80342400e-01 3.74406381e-09 1.61929065e-06
  1.69684481e-06]
 [1.44063357e-03 8.85442749e-07 5.90181156e-04 4.94679086e-09
  6.45817898e-06 6.79650915e-06 1.48815496e-02 5.13522643e-10
  1.48495258e-07]]

 The output layer has a (3, 9) matrix.
